### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [yvoxsproject/TeaCozy#5]
(Exceeds Expectations)

Nicely done on this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. And great job with the use of classes and IDs for styling your elements and creating hyperlinks! One thing to look out for is ways to simplify your code and omit unneeded items (#3).

As a further challenge, try expanding this page and play around with adding some of your own elements to it. As you do, think about the ways to most effectively write the code and avoid repetition whenever possible. Have fun!

**Comment by yvoxsproject** [comment]
Thanks for the feedback! I'll look out for unnecessary items next time :)
